# configure-prometheus-grafana.yml

---
- name: Configure Prometheus and Grafana
  hosts: ec2_instance
  become: yes

  tasks:
    - name: Install Prometheus
      yum:
        name: prometheus
        state: present

    - name: Configure Prometheus
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml

    - name: Start Prometheus
      systemd:
        name: prometheus
        state: started

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Start Grafana
      systemd:
        name: grafana-server
        state: started
